version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-banking
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - banking-net

  banking-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-banking
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bank_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - banking-net

volumes:
  mysql_data:

networks:
  banking-net:
